[package]
name = "chemsim"
version = "0.1.0"
authors = ["Remy Goldschmidt <taktoa@gmail.com>"]

[dependencies]
piston_window = "0.80.*"

[lib]
name = "chemsim"
path = "src/lib.rs"

[[bin]]
name = "bin"
path = "src/main.rs"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
